Integral de 1.4-2 de la integral de 1-1.5 ln(x+2y) dy dx



In [8]:
import math
import scipy as sp
import matplotlib.pyplot as pl
import numpy as np


In [35]:
def F(x,y):
    return np.log(x+2*y)

def gauss2D_xw_ab(N,a,b,c,d):
    x,w= sp.special.roots_legendre(N)
    
    X = ((b-a)/2)*x +((b+a)/2), (((b-a)/2)*w)
    Y = ((d-c)/2)*x +((d+c)/2), (((d-c)/2)*w)
    
    return X, Y

In [58]:
def CuadGauss2D(N,f,a,b,c,d):

    S =0.0 
    Sx=0.0
    Sy=0.0
    Y,X= gauss2D_xw_ab(N,a,b,c,d)
    
    yj= Y[0]
    xi= X[0]
    
    wj= Y[1]
    wi= X[1]
    S= S + wi[i]*wj[j]*F(xi[i],yj[j])  
#se cambio para separar las umas para cada x, y
    
# for i in range(N):
#     for i in range(N):
#         Sx= Sx + wi[i]*F(xi[i], yj[j])
#     Sy = Sy + wj[j]*F(xi[i], yj[j])
# S = Sx + Sy
    return S

In [59]:
N=5
a,b= 1.4,2
c,d= 1, 1.5

gauss2D_xw_ab(N,a,b,c,d)

((array([1.42814605, 1.53845921, 1.7       , 1.86154079, 1.97185395]),
  array([0.07107807, 0.1435886 , 0.17066667, 0.1435886 , 0.07107807])),
 (array([1.02345504, 1.11538267, 1.25      , 1.38461733, 1.47654496]),
  array([0.05923172, 0.11965717, 0.14222222, 0.11965717, 0.05923172])))

In [60]:

sp.special.roots_legendre(10)

(array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
         0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653]),
 array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
        0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134]))

In [21]:

# y, w2= sp.special.roots_legendre(10)
